apiVersion: v1
kind: Service
metadata:
  name: trade-capture
  namespace: pms
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8082"
spec:
  selector:
    app: trade-capture
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP
