apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation
  namespace: pms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulation
  template:
    metadata:
      labels:
        app: simulation
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done']
      - name: wait-for-rabbitmq
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z rabbitmq 5552; do echo waiting for rabbitmq stream; sleep 2; done']
      containers:
      - name: simulation
        image: niishantdev/pms-simulation:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_STREAM_PORT
          value: "5552"
        - name: RABBITMQ_STREAM_NAME
          value: "trade-stream"
        - name: DB_HOST
          value: "postgres"
        - name: DB_NAME
          value: "pmsdb"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/pmsdb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "pms"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "pms"
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "org.postgresql.Driver"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.PostgreSQLDialect"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: SCHEMA_REGISTRY_URL
          value: "http://schema-registry:8081"
        - name: SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL
          value: "http://schema-registry:8081"
