apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Use the official Argo CD install manifest as the source of truth
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
