apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: pms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      enableServiceLinks: false
      hostname: schema-registry
      containers:
      - name: schema-registry
        image: confluentinc/cp-schema-registry:7.5.0
        command:
          - /bin/bash
          - -c
          - |
            unset SCHEMA_REGISTRY_PORT
            unset SCHEMA_REGISTRY_SERVICE_PORT
            unset PORT
            /etc/confluent/docker/run
        ports:
        - containerPort: 8081
        env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: "schema-registry"
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: "PLAINTEXT://kafka:19092"
        - name: SCHEMA_REGISTRY_LISTENERS
          value: "http://0.0.0.0:8081"
