# Dev environment replica configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation
  namespace: pms
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-capture
  namespace: pms
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-service
  namespace: pms
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: pms
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: pms
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: pms
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: pms
spec:
  replicas: 1
